name: CI

on:
  push:
    branches:
      - main

env:
  GIT_USER: jolpizza
  GIT_EMAIL: joeylovepizzatoo@gmail.com
  THEME_REPO: iGuan7u/Acetolog
  THEME_BRANCH: master
  DEPLOY_REPO: jolpizza/jolpizza.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/Acetolog

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo -e "Host jolpizza\n   HostName github.com\n   User git\n   IdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config

          echo "$GRAPHVIZ_FOOTER_CODE" >> ~/work/jolpizza.github.com/jolpizza.github.com/themes/Acetolog/layout/includes/footer.swig

          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy hexo
        run: |
          npm run deploy --generate